//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTRentalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int HolidayId { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime DateOfHoliday { get; set; }
        public bool IsRecurringDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
