//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTRentalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTransactionDeliveryView
    {
        public int SaleTransactionId { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal TransactionAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public string CurrencyCode { get; set; }
        public int StoreLocationId { get; set; }
        public int CustomerId { get; set; }
        public int PaymentTermsInDays { get; set; }
        public decimal PaidAmount { get; set; }
        public string TransactionCategory { get; set; }
        public bool CustomerTaxExempted { get; set; }
        public int CustomerTypeId { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string SiteAddressLine1 { get; set; }
        public string SiteAddressLine2 { get; set; }
        public string SiteCity { get; set; }
        public Nullable<bool> VoidRequested { get; set; }
        public string VoidRequestReason { get; set; }
        public string VoidRequestedBy { get; set; }
        public Nullable<System.DateTime> VoidRequestDate { get; set; }
        public string VoidRequestStatusId { get; set; }
        public string VoidStatusEffectedBy { get; set; }
        public Nullable<System.DateTime> VoidStatusEffectedDate { get; set; }
        public decimal DeliveryCost { get; set; }
        public bool RequirePickup { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public int InventoryId { get; set; }
        public string UnitOfRentId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Period { get; set; }
        public decimal UnitCost { get; set; }
        public decimal TaxRate { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> TotalReturnedQuantity { get; set; }
        public decimal TotalDiscountAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string ContactNo1 { get; set; }
        public int ContactType1Id { get; set; }
        public string ContactNo2 { get; set; }
        public Nullable<int> ContactType2Id { get; set; }
        public string FaxNo { get; set; }
        public string EmailAddress { get; set; }
        public decimal PurchaseCost { get; set; }
        public decimal BookCost { get; set; }
        public decimal UseFulLifeCost { get; set; }
        public decimal LastCost { get; set; }
        public bool IsTaxable { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string UnitOfMeasureDescription { get; set; }
        public Nullable<decimal> ExtPrice { get; set; }
        public string PreparedBy { get; set; }
        public decimal SecurityDepositAmount { get; set; }
        public Nullable<bool> SecurityDepositReturned { get; set; }
        public Nullable<System.DateTime> DateSecurityDepositReturned { get; set; }
        public string SecurityDepositReturnedBy { get; set; }
        public bool DeliveryRequired { get; set; }
        public decimal SubTotalAmount { get; set; }
        public Nullable<decimal> TotalQuantityDelivered { get; set; }
        public int SaleTransactionDetailId { get; set; }
        public string SerialNo { get; set; }
        public string Model { get; set; }
        public string StoreName { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<int> RelativeSaleTransactionDetailId { get; set; }
        public decimal TransactionTaxRate { get; set; }
        public string DeliveryNo { get; set; }
        public Nullable<System.DateTime> ActualRentalStartDate { get; set; }
        public Nullable<System.DateTime> ActualRentalReturnDueDate { get; set; }
        public int SaleTransactionDeliveryDetailId { get; set; }
        public int SaleTransactionDeliveryId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal QuantityDelivered { get; set; }
        public string ItemNo { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string BrandName { get; set; }
        public string SizeDescription { get; set; }
    }
}
