//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMARTRentalManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalManagementDBEntities : DbContext
    {
        public RentalManagementDBEntities()
            : base("name=RentalManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SystemSecurityConfiguration> SystemSecurityConfigurations { get; set; }
        public virtual DbSet<SystemUserSetting> SystemUserSettings { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SaleTransactionView> SaleTransactionViews { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<SysUserAuditView> SysUserAuditViews { get; set; }
        public virtual DbSet<SaleTransactionDeliveryView> SaleTransactionDeliveryViews { get; set; }
    }
}
